# Project Overview:

In [1]:
# Import data exploration Liberaries:

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
# Load Dataset:

bridge_data = pd.read_csv('../data/bridge_digital_twin_dataset.csv')

bridge_data.head()

,Timestamp,Strain_microstrain,Deflection_mm,Vibration_ms2,Tilt_deg,Displacement_mm,Crack_Propagation_mm,Corrosion_Level_percent,Cable_Member_Tension_kN,Bearing_Joint_Forces_kN,...,Soil_Saturation_percent,Landslide_Ground_Movement,Simulated_Slope_Displacement_mm,High_Winds_Storms,Simulated_Wind_Load_Pressure_kPa,Abnormal_Traffic_Load_Surges,Simulated_Localized_Stress_Index,Energy_Harvesting_Potential_W,Estimated_Repair_Cost_USD_incremental,Carbon_Footprint_tCO2e_incremental
0,2023-01-01 00:00:00,NaN,12.663104,1.275955,0.587340,22.576518,-0.000083,0.002910,404.394906,233.052345,...,9.888758,0.0,0.022592,0.0,0.211946,0.0,0.215354,0.081403,1.343588,0.001348
1,2023-01-01 00:01:00,599.936448,12.235297,0.716857,0.657122,21.202649,0.000092,0.004601,367.821051,237.545735,...,9.920331,0.0,0.014647,0.0,0.231188,0.0,0.218747,0.107097,1.397207,0.001299
2,2023-01-01 00:02:00,573.878472,12.447144,0.834753,0.615011,NaN,-0.000377,0.005115,402.393742,239.164832,...,NaN,0.0,0.000000,0.0,0.199192,0.0,0.213449,0.141938,1.318876,0.001378
3,2023-01-01 00:03:00,550.457302,12.554883,1.004917,0.617999,21.551945,-0.000646,0.005505,356.024238,237.645586,...,43.526026,0.0,0.000000,0.0,0.198359,0.0,0.208190,0.192431,1.351773,0.001379
4,2023-01-01 00:04:00,572.829960,12.598818,1.176253,0.633534,21.711292,0.000247,-0.003415,413.338280,232.310381,...,44.138185,0.0,0.000000,0.0,0.188110,0.0,0.261240,0.261609,NaN,0.001267

In [3]:
bridge_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43200 entries, 0 to 43199
Data columns (total 54 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Timestamp                              43200 non-null  object
 1   Strain_microstrain                     41379 non-null  float64
 2   Deflection_mm                          41467 non-null  float64
 3   Vibration_ms2                          41478 non-null  float64
 4   Tilt_deg                               41447 non-null  float64
 5   Displacement_mm                        41473 non-null  float64
 6   Crack_Propagation_mm                   41494 non-null  float64
 7   Corrosion_Level_percent                41531 non-null  float64
 8   Cable_Member_Tension_kN                41459 non-null  float64
 9   Bearing_Joint_Forces_kN                41515 non-null  float64
 10  Fatigue_Accumulation_au                41496 non-null  float64
 11  Modal_Frequency_Hz                     41481 non-null  float64
 12  Temperature_C                          41457 non-null  float64
 13  Humidity_percent                       41417 non-null  float64
 14  Wind_Speed_ms                          41474 non-null  float64
 15  Wind_Direction_deg                     41432 non-null  float64
 16  Precipitation_mmh                      41513 non-null  float64
 17  Water_Level_m                          41513 non-null  float64
 18  Seismic_Activity_ms2                   41507 non-null  float64
 19  Solar_Radiation_Wm2                    41472 non-null  float64
 20  Air_Quality_Index_AQI                  41461 non-null  float64
 21  Soil_Settlement_mm                     41502 non-null  float64
 22  Vehicle_Load_tons                      41444 non-null  float64
 23  Traffic_Volume_vph                     41456 non-null  float64
 24  Pedestrian_Load_pph                    41473 non-null  float64
 25  Impact_Events_g                        41482 non-null  float64
 26  Dynamic_Load_Distribution_percent      41539 non-null  float64
 27  Axle_Counts_pmin                       41500 non-null  float64
 28  Structural_Health_Index_SHI            41500 non-null  float64
 29  Anomaly_Detection_Score                41494 non-null  float64
 30  Energy_Dissipation_au                  41506 non-null  float64
 31  Acoustic_Emissions_levels              41479 non-null  float64
 32  Visual_Analysis_Defect_Score           41465 non-null  float64
 33  Electrical_Resistance_ohms             41454 non-null  float64
 34  Bridge_Mood_Meter                      41490 non-null  object
 35  Localized_Strain_Hotspot               41446 non-null  float64
 36  Vibration_Anomaly_Location             9045 non-null   object
 37  SHI_Predicted_24h_Ahead                41538 non-null  float64
 38  SHI_Predicted_7d_Ahead                 41554 non-null  float64
 39  SHI_Predicted_30d_Ahead                41462 non-null  float64
 40  Probability_of_Failure_PoF             41456 non-null  float64
 41  Maintenance_Alert                      41504 non-null  float64
 42  Flood_Event_Flag                       41457 non-null  float64
 43  Simulated_Water_Flow_m3s               41494 non-null  float64
 44  Soil_Saturation_percent                41453 non-null  float64
 45  Landslide_Ground_Movement              41435 non-null  float64
 46  Simulated_Slope_Displacement_mm        41499 non-null  float64
 47  High_Winds_Storms                      41442 non-null  float64
 48  Simulated_Wind_Load_Pressure_kPa       41476 non-null  float64
 49  Abnormal_Traffic_Load_Surges           41437 non-null  float64
 50  Simulated_Localized_Stress_Index       41482 non-null  float64
 51  Energy_Harvesting_Potential_W          41471 non-null  float64
 52  Estimated_Repair_Cost_USD_incremental  41429 non-null  float64
 53  Carbon_Footprint_tCO2e_incremental     41476 non-null  float64
dtypes: float64(51), object(3)
memory usage: 17.8+ MB

In [4]:
bridge_data.columns

Index(['Timestamp', 'Strain_microstrain', 'Deflection_mm', 'Vibration_ms2',
       'Tilt_deg', 'Displacement_mm', 'Crack_Propagation_mm',
       'Corrosion_Level_percent', 'Cable_Member_Tension_kN',
       'Bearing_Joint_Forces_kN', 'Fatigue_Accumulation_au',
       'Modal_Frequency_Hz', 'Temperature_C', 'Humidity_percent',
       'Wind_Speed_ms', 'Wind_Direction_deg', 'Precipitation_mmh',
       'Water_Level_m', 'Seismic_Activity_ms2', 'Solar_Radiation_Wm2',
       'Air_Quality_Index_AQI', 'Soil_Settlement_mm', 'Vehicle_Load_tons',
       'Traffic_Volume_vph', 'Pedestrian_Load_pph', 'Impact_Events_g',
       'Dynamic_Load_Distribution_percent', 'Axle_Counts_pmin',
       'Structural_Health_Index_SHI', 'Anomaly_Detection_Score',
       'Energy_Dissipation_au', 'Acoustic_Emissions_levels',
       'Visual_Analysis_Defect_Score', 'Electrical_Resistance_ohms',
       'Bridge_Mood_Meter', 'Localized_Strain_Hotspot',
       'Vibration_Anomaly_Location', 'SHI_Predicted_24h_Ahead',
       'SHI_Predicted_7d_Ahead', 'SHI_Predicted_30d_Ahead',
       'Probability_of_Failure_PoF', 'Maintenance_Alert', 'Flood_Event_Flag',
       'Simulated_Water_Flow_m3s', 'Soil_Saturation_percent',
       'Landslide_Ground_Movement', 'Simulated_Slope_Displacement_mm',
       'High_Winds_Storms', 'Simulated_Wind_Load_Pressure_kPa',
       'Abnormal_Traffic_Load_Surges', 'Simulated_Localized_Stress_Index',
       'Energy_Harvesting_Potential_W',
       'Estimated_Repair_Cost_USD_incremental',
       'Carbon_Footprint_tCO2e_incremental'],
      dtype='object')

In [5]:
bridge_data.describe().T

,count,mean,std,min,25%,50%,75%,max
Strain_microstrain,41379.0,851.950836,351.908310,363.529753,618.866446,7.344767e+02,1072.661680,4074.893156
Deflection_mm,41467.0,15.145403,3.824032,6.889697,12.447132,1.498616e+01,17.090508,30.389080
Vibration_ms2,41478.0,1.339495,0.979641,0.637735,1.000030,1.198123e+00,1.532924,15.086480
Tilt_deg,41447.0,0.756122,0.142167,0.476074,0.667321,7.242946e-01,0.832503,1.522738
Displacement_mm,41473.0,22.703596,1.627841,18.964441,21.387484,2.236144e+01,23.985103,27.630262
Crack_Propagation_mm,41494.0,0.015036,0.009338,-0.001531,0.007511,1.502423e-02,0.022526,0.519706
Corrosion_Level_percent,41531.0,0.149950,0.086731,-0.010256,0.074979,1.501009e-01,0.224839,0.312679
Cable_Member_Tension_kN,41459.0,476.054924,91.773467,334.045442,396.924817,4.478997e+02,556.362810,844.862138
Bearing_Joint_Forces_kN,41515.0,276.967988,45.590840,205.758025,237.447819,2.600760e+02,318.127839,423.909686
Fatigue_Accumulation_au,41496.0,0.300012,0.173392,-0.022617,0.149817,2.998104e-01,0.450031,0.623392
Modal_Frequency_Hz,41481.0,1.895313,0.100269,1.353801,1.825477,1.895834e+00,1.968278,2.235211
Temperature_C,41457.0,14.997212,7.915274,-1.068778,8.796149,1.501107e+01,21.230163,30.980499
Humidity_percent,41417.0,60.345060,11.106635,38.697259,49.712584,6.028373e+01,70.689162,97.771977
Wind_Speed_ms,41474.0,6.557041,1.974331,2.550538,5.219239,6.509281e+00,7.810874,30.400091
Wind_Direction_deg,41432.0,180.130876,68.698291,31.331421,122.479158,1.803934e+02,237.878405,327.343142
Precipitation_mmh,41513.0,0.267975,3.001726,-0.034215,-0.005424,1.256661e-04,0.005667,40.003892
Water_Level_m,41513.0,2.031313,0.386359,1.754335,1.959667,2.000558e+00,2.042483,8.112134
Seismic_Activity_ms2,41507.0,0.000178,0.008015,-0.000022,-0.000003,2.646715e-09,0.000004,0.799996
Solar_Radiation_Wm2,41472.0,384.638724,373.416168,-42.409861,1.374895,4.465439e+02,768.133655,939.206016
Air_Quality_Index_AQI,41461.0,55.017205,14.519621,24.665229,41.382282,5.506796e+01,68.686540,83.519495
Soil_Settlement_mm,41502.0,0.301130,0.191159,-0.028364,0.149878,2.997726e-01,0.449531,5.494549
Vehicle_Load_tons,41444.0,17.965952,10.483328,5.882687,8.748282,1.638649e+01,29.045748,53.413615
Traffic_Volume_vph,41456.0,924.951021,539.448333,334.835289,450.251914,8.532223e+02,1500.804537,2758.136081
Pedestrian_Load_pph,41473.0,143.625976,83.621795,64.777263,85.476893,9.634307e+01,202.029503,413.164005
Impact_Events_g,41482.0,0.000193,0.027774,-0.000022,-0.000004,6.443804e-09,0.000004,4.000010
Dynamic_Load_Distribution_percent,41539.0,90.086584,6.394846,71.061275,85.056414,9.012694e+01,95.174346,108.173192
Axle_Counts_pmin,41500.0,50.653698,28.963567,16.348484,25.007156,4.341921e+01,73.715275,105.184466
Structural_Health_Index_SHI,41500.0,0.815885,0.052818,0.292081,0.797134,8.229360e-01,0.845468,0.907657
Anomaly_Detection_Score,41494.0,0.008795,0.069108,0.000000,0.000000,0.000000e+00,0.000000,1.000000
Energy_Dissipation_au,41506.0,0.273241,1.263164,0.016281,0.102124,1.562860e-01,0.255973,22.498957
Acoustic_Emissions_levels,41479.0,8.261512,5.219054,0.311427,3.250532,1.045003e+01,13.254671,28.085219
Visual_Analysis_Defect_Score,41465.0,0.004205,0.002521,0.000000,0.002105,4.195448e-03,0.006293,0.105542
Electrical_Resistance_ohms,41454.0,0.281876,0.029464,0.222124,0.256750,2.818049e-01,0.306667,0.349059
Localized_Strain_Hotspot,41446.0,0.004391,0.066122,0.000000,0.000000,0.000000e+00,0.000000,1.000000
SHI_Predicted_24h_Ahead,41538.0,0.812885,0.052718,0.289385,0.794093,8.199999e-01,0.842527,0.905986
SHI_Predicted_7d_Ahead,41554.0,0.795788,0.053037,0.262701,0.776798,8.032010e-01,0.825863,0.890325
SHI_Predicted_30d_Ahead,41462.0,0.750584,0.056366,0.197384,0.726813,7.573786e-01,0.785673,0.870487
Probability_of_Failure_PoF,41456.0,0.034029,0.017626,0.019160,0.027351,3.068917e-02,0.035370,0.708676
Maintenance_Alert,41504.0,0.006120,0.077991,0.000000,0.000000,0.000000e+00,0.000000,1.000000
Flood_Event_Flag,41457.0,0.004535,0.067189,0.000000,0.000000,0.000000e+00,0.000000,1.000000
Simulated_Water_Flow_m3s,41494.0,232.689308,50.240560,196.985886,223.399244,2.286341e+02,234.016599,1000.000000
Soil_Saturation_percent,41453.0,25.467336,15.769136,9.888758,10.001720,3.142082e+01,40.644940,68.376629
Landslide_Ground_Movement,41435.0,0.000072,0.008509,0.000000,0.000000,0.000000e+00,0.000000,1.000000
Simulated_Slope_Displacement_mm,41499.0,0.764185,0.808539,0.000000,0.375525,7.497037e-01,1.123895,63.736106
High_Winds_Storms,41442.0,0.002099,0.045771,0.000000,0.000000,0.000000e+00,0.000000,1.000000
Simulated_Wind_Load_Pressure_kPa,41476.0,0.199037,0.088777,0.113733,0.157449,1.894521e-01,0.228776,2.000000
Abnormal_Traffic_Load_Surges,41437.0,0.003186,0.056351,0.000000,0.000000,0.000000e+00,0.000000,1.000000
Simulated_Localized_Stress_Index,41482.0,0.461482,0.270107,0.149282,0.224376,3.756158e-01,0.698968,1.000000
Energy_Harvesting_Potential_W,41471.0,1.367458,6.316389,0.081403,0.510641,7.821733e-01,1.278369,112.494785
Estimated_Repair_Cost_USD_incremental,41429.0,313.237508,3934.070479,0.989533,1.518210,1.699154e+00,1.949163,50014.211024
Carbon_Footprint_tCO2e_incremental,41476.0,0.001852,0.000566,0.000901,0.001470,1.670360e-03,0.002218,0.003920